FROM alfresco/alfresco-content-repository-community:6.0.7-ga

RUN echo 'grant codeBase "file:/usr/local/tomcat/modules/platform/-" {permission  java.lang.reflect.ReflectPermission "suppressAccessChecks";};' >> conf/catalina.policy
