version: "3"

services:
    alfresco:
        image: pleosoft/alfresco:6.0.7-ga
        environment:
            JAVA_OPTS : "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dshare.host=localhost
                -Ddeployment.method=DOCKER_COMPOSE
                -Dcsrf.filter.enabled=false
                "
        volumes:
            - ./config/alfresco.xml:/usr/local/tomcat/conf/Catalina/localhost/alfresco.xml
            - ./config/alfresco-global.properties:/usr/local/tomcat/shared/classes/alfresco-global.properties
            - ./modules/platform:/usr/local/tomcat/modules/platform
            - ./data/alf_data:/usr/local/tomcat/alf_data
            - ./logs/alfresco:/usr/local/tomcat/logs
            
        ports:
            - 8082:8080 #Browser port
        
        networks:
            - pleosoft

    share:
        image: alfresco/alfresco-share:6.0.b
        environment:
            - REPO_HOST=alfresco
            - REPO_PORT=8080
        volumes:
            - ./logs/share:/usr/local/tomcat/logs
        ports:
            - 8080:8080
        networks:
            - pleosoft

    postgres:
        image: postgres:10.1
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        command: postgres -c max_connections=300 -c log_min_messages=LOG
        #volumes:
        #    - ./data/postgresql-data:/var/lib/postgresql/data
        #    - ./logs/postgresql:/var/log/postgresql
        ports:
            - 5432:5432   
        networks:
            - pleosoft

    solr6:
        image: alfresco/alfresco-search-services:1.1.1
        environment:
            #Solr needs to know how to register itself with Alfresco
            - SOLR_ALFRESCO_HOST=alfresco
            - SOLR_ALFRESCO_PORT=8080
            #Alfresco needs to know how to call solr
            - SOLR_SOLR_HOST=solr6
            - SOLR_SOLR_PORT=8983
            #Create the default alfresco and archive cores
            - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
        volumes:
            - ./data/solr-data:/opt/alfresco-search-services/data
        ports:
            - 8083:8983 #Browser port
         
        networks:
            - pleosoft
networks:
    pleosoft:
